// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"game_of_life/server/internal/grid/source"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGrid creates a new instance of MockGrid. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrid(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrid {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGrid{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGrid is an autogenerated mock type for the Grid type
type MockGrid struct {
	mock.Mock
}

type MockGrid_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrid) EXPECT() *MockGrid_Expecter {
	return &MockGrid_Expecter{mock: &_m.Mock}
}

// Advance provides a mock function for the type MockGrid
func (_mock *MockGrid) Advance() {
	_mock.Called()
	return
}

// MockGrid_Advance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Advance'
type MockGrid_Advance_Call struct {
	*mock.Call
}

// Advance is a helper method to define mock.On call
func (_e *MockGrid_Expecter) Advance() *MockGrid_Advance_Call {
	return &MockGrid_Advance_Call{Call: _e.mock.On("Advance")}
}

func (_c *MockGrid_Advance_Call) Run(run func()) *MockGrid_Advance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGrid_Advance_Call) Return() *MockGrid_Advance_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGrid_Advance_Call) RunAndReturn(run func()) *MockGrid_Advance_Call {
	_c.Run(run)
	return _c
}

// Current provides a mock function for the type MockGrid
func (_mock *MockGrid) Current() source.Frame {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 source.Frame
	if returnFunc, ok := ret.Get(0).(func() source.Frame); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(source.Frame)
		}
	}
	return r0
}

// MockGrid_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockGrid_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
func (_e *MockGrid_Expecter) Current() *MockGrid_Current_Call {
	return &MockGrid_Current_Call{Call: _e.mock.On("Current")}
}

func (_c *MockGrid_Current_Call) Run(run func()) *MockGrid_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGrid_Current_Call) Return(frame source.Frame) *MockGrid_Current_Call {
	_c.Call.Return(frame)
	return _c
}

func (_c *MockGrid_Current_Call) RunAndReturn(run func() source.Frame) *MockGrid_Current_Call {
	_c.Call.Return(run)
	return _c
}
