// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"game_of_life/server/internal/grid"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Next provides a mock function for the type MockSource
func (_mock *MockSource) Next() grid.Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 grid.Snapshot
	if returnFunc, ok := ret.Get(0).(func() grid.Snapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(grid.Snapshot)
	}
	return r0
}

// MockSource_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockSource_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockSource_Expecter) Next() *MockSource_Next_Call {
	return &MockSource_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockSource_Next_Call) Run(run func()) *MockSource_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Next_Call) Return(snapshot grid.Snapshot) *MockSource_Next_Call {
	_c.Call.Return(snapshot)
	return _c
}

func (_c *MockSource_Next_Call) RunAndReturn(run func() grid.Snapshot) *MockSource_Next_Call {
	_c.Call.Return(run)
	return _c
}
